### ISSUE TITLE
Unable to determine source from module subfolder

### ISSUE THREAD

**Issue by jlroettger** [dkundel/vscode-npm-source#1]
I like this extension, but ran into a limitation.

If you import a module from a subfolder, e.g. `import IconButton from 'material-ui/IconButton'`, the extension returns "Error: No repository found!." It would be nice if it climbed its way up the tree by stripping subfolders until it found an existing package.

**Comment by dkundel** [comment]
Thanks for your contribution! I merged your changes and will be releasing a new version today that contains your changes. Sorry for the delay.
